// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA42UjvLXX12WBGfkoD0stwY3Msn9AKkZ4',
    appId: '1:832707779202:web:b6f262f73837c8372fb29b',
    messagingSenderId: '832707779202',
    projectId: 'hw2-chatboards-app',
    authDomain: 'hw2-chatboards-app.firebaseapp.com',
    storageBucket: 'hw2-chatboards-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBhx_ET-m1J-1tFhcLr44DnAaZUJKghVE',
    appId: '1:832707779202:android:8444239ef893eece2fb29b',
    messagingSenderId: '832707779202',
    projectId: 'hw2-chatboards-app',
    storageBucket: 'hw2-chatboards-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbUbfksWHNm8GNFBAHEFlfS8ErqFw7TTI',
    appId: '1:832707779202:ios:334b42954faa295e2fb29b',
    messagingSenderId: '832707779202',
    projectId: 'hw2-chatboards-app',
    storageBucket: 'hw2-chatboards-app.firebasestorage.app',
    iosBundleId: 'com.example.hw02ChatboardsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbUbfksWHNm8GNFBAHEFlfS8ErqFw7TTI',
    appId: '1:832707779202:ios:334b42954faa295e2fb29b',
    messagingSenderId: '832707779202',
    projectId: 'hw2-chatboards-app',
    storageBucket: 'hw2-chatboards-app.firebasestorage.app',
    iosBundleId: 'com.example.hw02ChatboardsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA42UjvLXX12WBGfkoD0stwY3Msn9AKkZ4',
    appId: '1:832707779202:web:80f1c809ef9519462fb29b',
    messagingSenderId: '832707779202',
    projectId: 'hw2-chatboards-app',
    authDomain: 'hw2-chatboards-app.firebaseapp.com',
    storageBucket: 'hw2-chatboards-app.firebasestorage.app',
  );
}
